# devH2 -- H2 development profile

spring:
  include:
    - default
    
  datasource:
#    driver-class-name: org.h2database.jdbcDriver
    url: jdbc:h2:mem:dmc

# for H2 console frame
security:
  headers: 
    frame: false
        
logging:
  level:
    org.springframework: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: WARN
    org.springframework.data: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.webflow: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    evm.dmc.web: DEBUG
    evm.dmc.api: DEBUG

views2:
  showtable: /showtable/table
  hellorest:  /helloREST