endpoints:
  shutdown:
    enabled: true

#Management Configuration
management:
  security:
    enabled: false
  
  port: 9001
  context-path: /management
    
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

spring:
  thymeleaf:
#    check-template-location: true
    cache: false
#    prefix: classpath:templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
#    view-names: thymeleaf/*
#    suffix: .html
  

# Server Port Configuration
server:
  port: 8080
#Access log configuration
  tomcat:
    ccessLogEnabled: true
    basedir: ../logs
    accessLogPattern: "%t %s %a %D %r %b"

# Logging Configuration
logging:
#  config: log4j2.xml
  level:
    org.springframework.web: INFO
    evm.dmc.web: DEBUG
  file: ../logs/dmc-web.log

views2:
  showtable: /showtable/table
  hellorest:  /helloREST
#welcome:
#  message: "Hello ID#cat:)!!"
#  
#service:
#  message: Hello Alex