endpoints:
  shutdown:
    enabled: true

#Management Configuration
management:
  security:
    enabled: false
  
  port: 9001
  context-path: /management
    
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

spring:
  view:
    prefix: /WEB-INF/
    suffix: .jsp
    view-names: jsp/*
  thymeleaf:
    view-names: thymeleaf/*

# Server Port Configuration
server:
  port: 8080
#Access log configuration
  tomcat:
    ccessLogEnabled: true
    basedir: ../logs
    accessLogPattern: "%t %s %a %D %r %b"

# Logging Configuration
logging:
#  config: log4j2.xml
  level:
    org.springframework.web: INFO
    evm.dmc.web: DEBUG
  file: ../logs/dmc-web.log
  
welcome:
  message: "Hello ID#cat:)!!"
  
service:
  message: Hello Alex