views:
  index: index
  about: about
  register: register
  signin: signin
  regsign: "register_signin"
  home: userHome
  testing:
    testindex:  testing/testindex
    hello:  testing/hello?name=Alex
    hellorest:  testing/helloREST
    hellothyme: testing/helloThyme
    welcome:  /testing/welcome
    showtable:  /testing/showtable/table/0
    listbeans: /testing/showtable/listbeans
    createalg:  /createalg