views:
  index: index
  about: about
  register: register
  signin: signin
  regsign: "register_signin"
  regsig_fragment: " :: regsignForm(active='%s')"
  userHome: userHome
  adminHome: adminHome
  errors:
    accessDenied: errors/accessDenied
    notFound: errors/notFound
  testing:
    testindex:  testing/testindex
    hello:  testing/hello?name=Alex
    hellorest:  testing/helloREST
    hellothyme: testing/helloThyme
    welcome:  /testing/welcome
    showtable:  /testing/showtable/table/0
    listbeans: /testing/showtable/listbeans
    createalg:  /createalg