views:
  testing:
    index:  testing/index
    hello:  testing/hello?name=Alex
    hellorest:  testing/helloREST
    hellothyme: testing/helloThyme
    welcome:  /testing/welcome
    showtable:  /testing/showtable/table/0
    listbeans: /testing/showtable/listbeans
    createalg:  /createalg